#!/bin/bash
# ============================================
# AI Sitemap Builder - Project Scaffold
# Generated by AI Project Planner v3.3
# ============================================

set -e  # Exit on error

echo "🚀 Setting up AI Sitemap Builder..."

# --------------------------------------------
# Check prerequisites
# --------------------------------------------
echo "📋 Checking prerequisites..."

if ! command -v node &> /dev/null; then
    echo "❌ Node.js is required but not installed."
    echo "   Install from: https://nodejs.org/"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "❌ npm is required but not installed."
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo "❌ Node.js 18+ is required. You have $(node -v)"
    exit 1
fi

echo "✅ Node.js $(node -v) detected"

# --------------------------------------------
# Initialize Next.js project
# --------------------------------------------
echo "📦 Creating Next.js project..."

# Create Next.js app with a valid npm name
npx create-next-app@latest ai-sitemap-builder --typescript --tailwind --eslint --app --src-dir=false --import-alias="@/*" --use-npm

# Move contents to current directory
mv ai-sitemap-builder/* ai-sitemap-builder/.[!.]* . 2>/dev/null || true
rm -rf ai-sitemap-builder

# --------------------------------------------
# Install additional dependencies
# --------------------------------------------
echo "⬇️  Installing dependencies..."

npm install @supabase/supabase-js @supabase/ssr @anthropic-ai/sdk axios cheerio xml2js zod react-hook-form @hookform/resolvers lucide-react class-variance-authority clsx tailwind-merge

npm install -D @types/xml2js prettier prettier-plugin-tailwindcss

# --------------------------------------------
# Set up shadcn/ui
# --------------------------------------------
echo "🎨 Setting up shadcn/ui..."

npx shadcn@latest init -y

# Install common components
npx shadcn@latest add button card input label textarea select dialog dropdown-menu toast form

# --------------------------------------------
# Create directory structure
# --------------------------------------------
echo "📁 Creating directories..."

mkdir -p app/\(auth\)/login
mkdir -p app/\(auth\)/register
mkdir -p app/\(dashboard\)/projects/\[id\]
mkdir -p app/\(dashboard\)/projects/new
mkdir -p app/\(dashboard\)/templates/\[id\]
mkdir -p app/api/auth/me
mkdir -p app/api/templates/\[id\]
mkdir -p app/api/projects/\[id\]/nodes/\[nodeId\]
mkdir -p app/api/projects/\[id\]/nodes/bulk
mkdir -p app/api/projects/\[id\]/export/csv
mkdir -p app/api/projects/\[id\]/export/json
mkdir -p app/api/crawl
mkdir -p app/api/ai/compare
mkdir -p components/features/auth
mkdir -p components/features/projects
mkdir -p components/features/templates
mkdir -p components/features/sitemap
mkdir -p components/features/crawler
mkdir -p components/features/services
mkdir -p components/features/locations
mkdir -p components/layouts
mkdir -p lib/supabase
mkdir -p lib/claude
mkdir -p lib/crawler
mkdir -p lib/utils
mkdir -p types
mkdir -p hooks
mkdir -p supabase/migrations

# --------------------------------------------
# Create placeholder files
# --------------------------------------------
echo "📄 Creating placeholder files..."

# Supabase clients
cat > lib/supabase/client.ts << 'EOF'
import { createBrowserClient } from '@supabase/ssr'

export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
}
EOF

cat > lib/supabase/server.ts << 'EOF'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

export async function createClient() {
  const cookieStore = await cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll()
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            )
          } catch {
            // Handle server component
          }
        },
      },
    }
  )
}
EOF

# API response utilities
cat > lib/utils/api-response.ts << 'EOF'
import { NextResponse } from 'next/server'

export function apiResponse<T>(data: T, status = 200) {
  return NextResponse.json({
    success: true,
    data,
    meta: { timestamp: new Date().toISOString() }
  }, { status })
}

export function apiError(code: string, message: string, status = 400) {
  return NextResponse.json({
    success: false,
    data: null,
    error: { code, message }
  }, { status })
}
EOF

# Types placeholder
cat > types/index.ts << 'EOF'
// Database types will be generated from Supabase
// Run: npx supabase gen types typescript --project-id <your-project-id> > types/database.ts

export interface Project {
  id: string
  name: string
  client_url: string | null
  template_id: string | null
  services_config: any[]
  locations: any[]
  status: string
  created_by: string
  created_at: string
  updated_at: string | null
}

export interface Template {
  id: string
  name: string
  description: string | null
  structure: any
  services: any[]
  is_active: boolean
  created_by: string
  created_at: string
}

export interface SitemapNode {
  id: string
  project_id: string
  title: string
  url: string | null
  page_type: 'standard' | 'service' | 'location' | 'service_location'
  parent_id: string | null
  source: 'template' | 'client'
  client_original_url: string | null
  position: number
}
EOF

# --------------------------------------------
# Set up environment
# --------------------------------------------
echo "🔧 Setting up environment..."

cat > .env.example << 'EOF'
# Supabase
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# Claude API
CLAUDE_API_KEY=sk-ant-api03-your-key

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

if [ ! -f .env.local ]; then
  cp .env.example .env.local
  echo "📝 Created .env.local - please fill in your values"
fi

# --------------------------------------------
# Create .gitignore additions
# --------------------------------------------
echo "📝 Updating .gitignore..."

cat >> .gitignore << 'EOF'

# Environment
.env.local
.env.production.local

# Supabase
supabase/.temp

# IDE
.idea
.vscode
EOF

# --------------------------------------------
# Create README
# --------------------------------------------
echo "📖 Creating README..."

cat > README.md << 'EOF'
# AI Sitemap Builder

AI-powered sitemap generator that compares client websites against templates.

## Getting Started

1. Install dependencies:
   ```bash
   npm install
   ```

2. Set up environment variables:
   - Copy `.env.example` to `.env.local`
   - Fill in your Supabase and Claude API credentials

3. Run database migrations:
   ```bash
   npx supabase db push
   ```

4. Start development server:
   ```bash
   npm run dev
   ```

## Documentation

See the `/documentation` folder or project root for:
- `01_PROJECT_REQUIREMENTS.md` - Requirements
- `02_TECH_STACK.md` - Technology choices
- `03_DATA_MODELS.md` - Database schema
- `04_API_SPECIFICATION.md` - API endpoints
- And more...

## Tech Stack

- **Frontend:** Next.js 14 (React)
- **Backend:** Next.js API Routes
- **Database:** Supabase (PostgreSQL)
- **Auth:** Supabase Auth
- **AI:** Claude API (Anthropic)
- **Hosting:** Railway

## Scripts

- `npm run dev` - Start development server
- `npm run build` - Build for production
- `npm run lint` - Run ESLint
- `npm run db:types` - Generate TypeScript types from Supabase
EOF

# --------------------------------------------
# Complete
# --------------------------------------------
echo ""
echo "✅ Scaffold complete!"
echo ""
echo "📋 Next steps:"
echo "  1. Fill in .env.local with your API credentials"
echo "  2. Create Supabase project at https://supabase.com"
echo "  3. Run database migrations (see supabase/migrations/)"
echo "  4. Start development: npm run dev"
echo ""
echo "📚 Documentation files are in the project root (01_*, 02_*, etc.)"
echo ""
echo "🚀 Run 'npm run dev' to start development."
